### ISSUE TITLE
[Feat]: Support multiple Terraform versions

### ISSUE THREAD

**Issue by hansohn** [hansohn/terraform-docker#10]
### Is your feature request related to a problem/challenge you are trying to solve?

Properly testing Terraform modules requires validating them at both the minimum and maximum supported version values declared within the versions.tf file. This poses 2 problems:

1. Storing multiple terraform modules to allow for module testing without needing to download additional versions at run time
2. Ability to switch between versions as needed

### Describe the solution you'd like

Potentially include minimum and maximum terraform versions from 0.14 on and use something like tfswitch or tfenv to target a particular version for use.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
